# Generated by Django 2.1.7 on 2019-04-07 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=1)),
                ('Answer_comment', models.TextField(default=None)),
                ('Time', models.TimeField(default=None)),
                ('Date', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('is_visible', models.BooleanField()),
                ('Answer_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BName', models.CharField(max_length=150)),
                ('Num_waiters', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SName', models.CharField(max_length=150)),
                ('Logo', models.ImageField(upload_to='pictures/Source_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Waiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_Name', models.CharField(max_length=150)),
                ('W_photo', models.ImageField(upload_to='pictures/waiters_photos/')),
                ('Branch_fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='surv.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='Source_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='surv.Source'),
        ),
        migrations.AddField(
            model_name='ask',
            name='Source_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='surv.Source'),
        ),
        migrations.AddField(
            model_name='ans',
            name='Question_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='surv.Ask'),
        ),
        migrations.AddField(
            model_name='ans',
            name='Waiter_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='surv.Waiters'),
        ),
        migrations.AddField(
            model_name='ans',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
