# Generated by Django 2.1.7 on 2019-04-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0003_person_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
