# Generated by Django 2.1.7 on 2019-04-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0005_auto_20190418_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
