# Generated by Django 2.1.7 on 2019-04-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0006_auto_20190418_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
