# Generated by Django 2.1.7 on 2019-04-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0007_auto_20190418_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
