# Generated by Django 2.1.7 on 2019-04-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0008_auto_20190418_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='incentive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.IntegerField(default=0, max_length=1, null=True),
        ),
    ]
