# Generated by Django 2.1.7 on 2019-04-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0009_auto_20190418_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
