# Generated by Django 2.1.7 on 2019-04-20 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0012_person_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='surv.person'),
        ),
    ]
