# Generated by Django 2.1.7 on 2019-04-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0014_auto_20190420_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='Answer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='rate',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
