# Generated by Django 2.1.7 on 2019-04-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_ask_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BName', models.TextField()),
                ('Num_waiters', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SName', models.TextField()),
                ('Logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Waiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_Name', models.TextField()),
                ('W_photo', models.ImageField(upload_to='')),
                ('Branch_fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.Branch')),
            ],
        ),
        migrations.RemoveField(
            model_name='ans',
            name='done',
        ),
        migrations.AddField(
            model_name='ans',
            name='Answer_comment',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='ans',
            name='Date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='ans',
            name='Time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='ask',
            name='Answer_type',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='ask',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='branch',
            name='Source_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.Source'),
        ),
        migrations.AddField(
            model_name='ans',
            name='Waiter_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.Waiters'),
        ),
        migrations.AddField(
            model_name='ask',
            name='Source_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.Source'),
        ),
    ]
