# Generated by Django 2.1.7 on 2019-04-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20190403_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='Answer_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ask',
            name='content',
            field=models.TextField(),
        ),
    ]
