# Generated by Django 2.1.7 on 2019-04-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20190404_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='Logo',
            field=models.ImageField(upload_to='pictures/Source_logos/'),
        ),
        migrations.AlterField(
            model_name='waiters',
            name='W_photo',
            field=models.ImageField(upload_to='pictures/waiters_photos/'),
        ),
    ]
